<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Content Remove="wwwroot\img\DMiniLogo.svg" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MailKit" Version="4.17.0" />
		<PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="2.3.10" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.15" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
		<PackageReference Include="MimeKit" Version="4.17.0" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="wwwroot\css\admin.css" />
	</ItemGroup>

</Project>